//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.ObjectSensors = new HashSet<ObjectSensor>();
            this.ObjectSensors1 = new HashSet<ObjectSensor>();
        }
    
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public bool EnableORDisable { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Min { get; set; }
        public string Max { get; set; }
        public string ImgPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectSensor> ObjectSensors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectSensor> ObjectSensors1 { get; set; }
    }
}
