//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Logins = new HashSet<Login>();
            this.OBJECTS = new HashSet<OBJECT>();
        }
    
        public int ClientID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int OperatorID { get; set; }
        public string Contact { get; set; }
        public string Code { get; set; }
        public bool Enabled { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBJECT> OBJECTS { get; set; }
    }
}
