//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandExecuteHistory
    {
        public long CommandExecuteHistoryID { get; set; }
        public int ObjectId { get; set; }
        public int CommandID { get; set; }
        public string Response { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ExecutedBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual OBJECT OBJECT { get; set; }
    }
}
