//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumptionReport
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SensorID { get; set; }
        public Nullable<double> Volt { get; set; }
        public Nullable<double> Cur { get; set; }
        public Nullable<double> Power { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> ObjectID { get; set; }
    }
}
