//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomNotification
    {
        public int NotificationID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> State { get; set; }
    }
}
