//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventConfiguration
    {
        public int EventConfigID { get; set; }
        public Nullable<long> ObjectSensorID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public double Min { get; set; }
        public double MAX { get; set; }
        public int Condition { get; set; }
        public Nullable<bool> EnableOrDisable { get; set; }
        public Nullable<double> A0 { get; set; }
        public Nullable<double> A1 { get; set; }
        public string Contact { get; set; }
        public string Units { get; set; }
        public string Format { get; set; }
    
        public virtual ObjectSensor ObjectSensor { get; set; }
        public virtual OBJECT OBJECT { get; set; }
    }
}
