//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSMSLog
    {
        public int ESLID { get; set; }
        public Nullable<int> EventLogID { get; set; }
        public string Object { get; set; }
        public string Location { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ObjectSensorID { get; set; }
        public string Value { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
    }
}
