//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.LoginFeatures = new HashSet<LoginFeature>();
            this.LoginGroups = new HashSet<LoginGroup>();
        }
    
        public int LoginID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string User { get; set; }
        public string Comment { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginFeature> LoginFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginGroup> LoginGroups { get; set; }
    }
}
