//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectSensor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectSensor()
        {
            this.EventConfigurations = new HashSet<EventConfiguration>();
            this.EventLogs = new HashSet<EventLog>();
            this.PMDATAs = new HashSet<PMDATA>();
            this.SensorInterpretations = new HashSet<SensorInterpretation>();
        }
    
        public long ObjectSensorId { get; set; }
        public int SensorID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> SMSAlert { get; set; }
        public Nullable<bool> EmailAlert { get; set; }
        public Nullable<double> A0 { get; set; }
        public Nullable<double> A1 { get; set; }
        public string Contact { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventConfiguration> EventConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventLog> EventLogs { get; set; }
        public virtual OBJECT OBJECT { get; set; }
        public virtual OBJECT OBJECT1 { get; set; }
        public virtual Sensor Sensor { get; set; }
        public virtual Sensor Sensor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMDATA> PMDATAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SensorInterpretation> SensorInterpretations { get; set; }
    }
}
