//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectCommand
    {
        public int CommandsQueueID { get; set; }
        public int ObjectID { get; set; }
        public int CommandID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual OBJECT OBJECT { get; set; }
    }
}
