//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectLastStatu
    {
        public int StatusID { get; set; }
        public Nullable<long> PMID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public string DeviceIP { get; set; }
        public bool DeviceStatus { get; set; }
        public System.DateTime ConnectionDatetime { get; set; }
        public Nullable<int> Priority { get; set; }
        public int DevicePort { get; set; }
        public Nullable<System.DateTime> LastRecordReceived { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual OBJECT OBJECT { get; set; }
        public virtual PMessage PMessage { get; set; }
    }
}
