//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectGroup
    {
        public int ObjectGroupID { get; set; }
        public int ObjectID { get; set; }
        public int GroupID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual OBJECT OBJECT { get; set; }
    }
}
