//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMDATA
    {
        public long PMDATAID { get; set; }
        public Nullable<long> PMID { get; set; }
        public Nullable<long> ObjectSensorId { get; set; }
        public string VALUE { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<int> SensorId { get; set; }
    
        public virtual ObjectSensor ObjectSensor { get; set; }
        public virtual PMessage PMessage { get; set; }
    }
}
