//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorObjectGroup
    {
        public int SensorObjectGroupID { get; set; }
        public Nullable<int> ROUT { get; set; }
        public Nullable<int> ROUTCurrent { get; set; }
        public Nullable<int> ROUTVoltage { get; set; }
        public Nullable<int> ROUTStatus { get; set; }
        public Nullable<int> ROUTFault { get; set; }
    }
}
