//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorControlling
    {
        public int SCID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<int> ObjectSensorID { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<int> Condition { get; set; }
        public Nullable<int> OnCommandID { get; set; }
        public Nullable<int> OffCommandID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<bool> RelayStatus { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
