//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorInterpretation
    {
        public long SensorInterpretationId { get; set; }
        public long ObjectSensorId { get; set; }
        public double MinValue { get; set; }
        public double MaxValue { get; set; }
        public string Meaning { get; set; }
    
        public virtual ObjectSensor ObjectSensor { get; set; }
    }
}
