//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsDinStatetemp
    {
        public int DinId { get; set; }
        public Nullable<int> PMID { get; set; }
        public Nullable<int> ObjectsensorId { get; set; }
        public Nullable<bool> Value { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> DatetimeStamp { get; set; }
    }
}
