//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSwitchReport
    {
        public int TempId { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Current { get; set; }
        public Nullable<double> Voltage { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Fault { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> C_SensorId { get; set; }
        public Nullable<int> V_SensorId { get; set; }
        public Nullable<int> S_SensorId { get; set; }
        public Nullable<int> LocationID { get; set; }
    }
}
