//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel_SMSGateway
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsToSend
    {
        public int SmsToSendId { get; set; }
        public string DestinationNumber { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CellNetworkId { get; set; }
        public Nullable<bool> IsEencrypted { get; set; }
    }
}
